[package]
name = "reader"
version = "0.1.0"
authors = ["Jamey Sharp <jamey@minilop.net>"]

[dependencies]
gio = "*"
glib = "*"
gtk = "*"
rss = { version = "*", features = ["from_url"] }
webkit2gtk = "*"
